[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 1 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on tokens per min (TPM): Limit 100000, Used 92064, Requested 8172. Please try again in 1h41m57.12s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 2.25 seconds. Total calls: 1
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 2 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 29.0 seconds. Total calls: 2
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 3 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 55.79700000002049 seconds. Total calls: 3
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 4 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on tokens per min (TPM): Limit 100000, Used 92061, Requested 8172. Please try again in 1h40m39.36s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 82.15600000001723 seconds. Total calls: 4
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 5 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 112.14100000000326 seconds. Total calls: 5
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 6 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on tokens per min (TPM): Limit 100000, Used 92059, Requested 8172. Please try again in 1h39m47.52s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 143.48399999999674 seconds. Total calls: 6
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 7 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 179.625 seconds. Total calls: 7
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 8 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 210.07800000003772 seconds. Total calls: 8
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 9 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on tokens per min (TPM): Limit 100000, Used 92054, Requested 8172. Please try again in 1h37m37.92s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 271.98399999999674 seconds. Total calls: 9
[1m[31mERROR   [0m pyrit.exceptions.exceptions_helpers:exceptions_helpers.py:21 Retry attempt 10 for _complete_chat_async failed with exception: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-b3VPqI3avWEHvKJXXHqps9cf on tokens per min (TPM): Limit 100000, Used 92051, Requested 8172. Please try again in 1h36m20.16s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}. Elapsed time: 348.125 seconds. Total calls: 10